name: Java GitHub CD with Maven

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Deploy Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github-snapshot # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy --file pom.xml -s settings.xml -Denv.USERNAME=${USERNAME} -Denv.PASSWORD=${PASSWORD} -Dmaven.test.skip=true -DaltDeploymentRepository=github-snapshot::default::https://maven.pkg.github.com/juliengalet/reactor-flow
        env:
          USERNAME: ${{github.actor}}
          PASSWORD: ${{github.token}}